#!/usr/bin/env python3
"""
test_dual_place.py

Dual-arm place-style test based on the previous test_dual_pick/test_dual_box flow.

Requested sequence:

1. Wait for an "arrived" signal.
   - For now, ARRIVED_SIGNAL_RECEIVED is hard-coded to True in USER CONFIG.
2. When arrived=True, keep the current arm posture and move only the lift to -0.25.
   - During this lift motion, no arm trajectory is sent.
   - The arm controllers are expected to hold their current joint positions.
3. After the lift reaches -0.25, move the arms to the previous wp1 pose.
   - When APPLY_LIFT_OFFSET_TO_PLACE_WAYPOINT=True, the place waypoint z value is
     adjusted by the current lift target. For LIFT_PLACE_DOWN=-0.25, wp1 z becomes
     wp1_z - 0.25.
   - The right arm trajectory is generated by mirroring the left trajectory.
4. After the arms reach the place waypoint, optionally return the lift to 0.0.

This file still uses direct controller execution for both arm trajectories:

     /arm_l_controller/follow_joint_trajectory
     /arm_r_controller/follow_joint_trajectory

and a direct FollowJointTrajectory action for the lift controller.
"""

from __future__ import annotations

import argparse
import math
import sys
import time
import traceback
from typing import Iterable

import rclpy
from action_msgs.msg import GoalStatus
from control_msgs.action import FollowJointTrajectory
from geometry_msgs.msg import Pose, PoseStamped
from moveit_msgs.msg import MoveItErrorCodes, RobotState
from moveit_msgs.srv import GetPositionIK
from rclpy.action import ActionClient
from rclpy.node import Node
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint

from ai_worker_manipulation.robot_interface.moveit_dual import (
    ARM_GROUP,
    ARM_EEF,
    ARM_L_JOINTS,
    ARM_R_JOINTS,
    BASE_LINK,
    Arm,
    SymmetricDualArmClient,
    duration_from_seconds,
)


# =============================================================================
# USER CONFIG - edit only this section for normal place testing
# =============================================================================

# Whether the robot should first move to the current symmetry reference pose.
HOME_FIRST = False

# Whether the robot should return to the symmetry reference pose after the test.
RETURN_HOME = False

# If True, plan trajectories but do not execute controller goals.
PLAN_ONLY = False

# For now, the arrival signal is represented by this boolean.
# Later, replace this with a ROS subscriber / action feedback / service result.
ARRIVED_SIGNAL_RECEIVED = True

# If True, after arrived=True, move the lift to LIFT_PLACE_DOWN before going to wp1.
# If False, skip the lift motion and go directly to wp1.
USE_LIFT_ON_ARRIVAL = True

# If True, when USE_LIFT_ON_ARRIVAL=True, apply the lift-down value to the place waypoint.
# Example: PLACE_WAYPOINT z=1.20 and LIFT_PLACE_DOWN=-0.25 -> planned z=0.95.
APPLY_LIFT_OFFSET_TO_PLACE_WAYPOINT = True

# If True, after reaching the place waypoint, move the lift back to LIFT_HOME.
RETURN_LIFT_HOME_AFTER_PLACE = True

# Use direct fixed-waypoint path generation before mirroring. This does not read GPD data.
# Set this to True only when intentionally using task_pose_selector pick-style filtering.
USE_TASK_SELECTOR = False
INCLUDE_TASK_TARGET = True
TASK_PRE_GRASP_OFFSET = 0.15

# Time spent moving from the current arm state to the place waypoint.
SEGMENT_DURATION_SEC = 4.0

# Number of interpolated joint trajectory points per segment.
POINTS_PER_SEGMENT = 25

# Controller action timeout.
TIMEOUT_SEC = 30.0

# Lift motion for place.
LIFT_HOME = 0.0
LIFT_PLACE_DOWN = -0.25
LIFT_MOVE_DURATION_SEC = 10.0
LIFT_TIMEOUT_SEC = 15.0

# Change these two names if your robot uses different lift controller / joint names.
LIFT_CONTROLLER_ACTION = "/lift_controller/follow_joint_trajectory"
LIFT_JOINT_NAME = "lift_joint"

# Previous waypoint1 pose from the earlier test_dual_pick/test_dual_box script.
# The LEFT arm is planned to this pose, then mirrored to the RIGHT arm.
PLACE_WAYPOINT = {
    "name": "wp1_place",
    "position": [0.5, 0.35, 1.2],
    # "quat": [0.0, 0.0, 0.0, 1.0],
    "rpy_deg": [-90.0, 0.0, 90.0],
}

# =============================================================================
# End of USER CONFIG
# =============================================================================


def normalize_quaternion(quat: Iterable[float]) -> tuple[float, float, float, float]:
    values = tuple(float(v) for v in quat)
    if len(values) != 4:
        raise ValueError("quaternion must have exactly 4 values: qx qy qz qw")
    qx, qy, qz, qw = values
    norm = math.sqrt(qx * qx + qy * qy + qz * qz + qw * qw)
    if norm < 1.0e-9:
        raise ValueError("quaternion norm is zero")
    return (qx / norm, qy / norm, qz / norm, qw / norm)


def quaternion_from_rpy_deg(
    roll_deg: float,
    pitch_deg: float,
    yaw_deg: float,
) -> tuple[float, float, float, float]:
    """Return qx, qy, qz, qw from roll/pitch/yaw in degrees."""
    roll = math.radians(float(roll_deg))
    pitch = math.radians(float(pitch_deg))
    yaw = math.radians(float(yaw_deg))

    cy = math.cos(yaw * 0.5)
    sy = math.sin(yaw * 0.5)
    cp = math.cos(pitch * 0.5)
    sp = math.sin(pitch * 0.5)
    cr = math.cos(roll * 0.5)
    sr = math.sin(roll * 0.5)

    qw = cr * cp * cy + sr * sp * sy
    qx = sr * cp * cy - cr * sp * sy
    qy = cr * sp * cy + sr * cp * sy
    qz = cr * cp * sy - sr * sp * cy
    return normalize_quaternion((qx, qy, qz, qw))


def make_pose_from_quat(x: float, y: float, z: float, quat: Iterable[float]) -> Pose:
    qx, qy, qz, qw = normalize_quaternion(quat)
    pose = Pose()
    pose.position.x = float(x)
    pose.position.y = float(y)
    pose.position.z = float(z)
    pose.orientation.x = qx
    pose.orientation.y = qy
    pose.orientation.z = qz
    pose.orientation.w = qw
    return pose


def waypoint_to_pose(waypoint: dict) -> tuple[str, Pose]:
    name = str(waypoint.get("name", "unnamed"))
    if "position" not in waypoint:
        raise ValueError(f"{name} is missing position: [x, y, z]")

    position = tuple(float(v) for v in waypoint["position"])
    if len(position) != 3:
        raise ValueError(f"{name} position must have exactly 3 values: x y z")

    if "quat" in waypoint and waypoint["quat"] is not None:
        quat = normalize_quaternion(waypoint["quat"])
    elif "rpy_deg" in waypoint and waypoint["rpy_deg"] is not None:
        rpy = tuple(float(v) for v in waypoint["rpy_deg"])
        if len(rpy) != 3:
            raise ValueError(f"{name} rpy_deg must have exactly 3 values")
        quat = quaternion_from_rpy_deg(rpy[0], rpy[1], rpy[2])
    else:
        raise ValueError(f"{name} must provide either quat or rpy_deg")

    pose = make_pose_from_quat(position[0], position[1], position[2], quat)
    return name, pose


def resolve_place_waypoint() -> tuple[str, Pose]:
    return waypoint_to_pose(PLACE_WAYPOINT)


def copy_pose_with_z_offset(pose: Pose, z_offset: float) -> Pose:
    copied = Pose()
    copied.position.x = pose.position.x
    copied.position.y = pose.position.y
    copied.position.z = pose.position.z + float(z_offset)
    copied.orientation = pose.orientation
    return copied


def pose_str(pose: Pose) -> str:
    p = pose.position
    q = pose.orientation
    return (
        f"pos=({p.x:.3f}, {p.y:.3f}, {p.z:.3f}), "
        f"quat=({q.x:.3f}, {q.y:.3f}, {q.z:.3f}, {q.w:.3f})"
    )


def wait_future(future, timeout_sec: float):
    deadline = time.time() + timeout_sec
    while not future.done():
        if time.time() > deadline:
            raise TimeoutError("future timeout")
        time.sleep(0.01)
    return future.result()


class LiftTrajectoryClient:
    """Small direct FollowJointTrajectory client for the vertical lift joint."""

    def __init__(
        self,
        node: Node,
        *,
        action_name: str = LIFT_CONTROLLER_ACTION,
        joint_name: str = LIFT_JOINT_NAME,
    ):
        self._node = node
        self._log = node.get_logger()
        self._action_name = action_name
        self._joint_name = joint_name
        self._client = ActionClient(node, FollowJointTrajectory, action_name)

    def move_to(
        self,
        position: float,
        *,
        duration_sec: float = LIFT_MOVE_DURATION_SEC,
        timeout_sec: float = LIFT_TIMEOUT_SEC,
    ) -> bool:
        if not self._client.wait_for_server(timeout_sec=timeout_sec):
            self._log.error(f"[lift] action server not available: {self._action_name}")
            return False

        traj = JointTrajectory()
        traj.joint_names = [self._joint_name]

        point = JointTrajectoryPoint()
        point.positions = [float(position)]
        point.velocities = [0.0]
        point.time_from_start = duration_from_seconds(duration_sec)
        traj.points.append(point)

        goal = FollowJointTrajectory.Goal()
        goal.trajectory = traj

        self._log.info(
            f"[lift] moving {self._joint_name} to {float(position):.3f} "
            f"via {self._action_name}"
        )

        try:
            send_future = self._client.send_goal_async(goal)
            goal_handle = wait_future(send_future, timeout_sec=timeout_sec)

            if goal_handle is None or not goal_handle.accepted:
                self._log.error("[lift] goal rejected")
                return False

            result_future = goal_handle.get_result_async()
            wrapped = wait_future(result_future, timeout_sec=timeout_sec + duration_sec + 2.0)

            status = int(getattr(wrapped, "status", GoalStatus.STATUS_UNKNOWN))
            result_msg = getattr(wrapped, "result", None)
            error_code = getattr(result_msg, "error_code", 0)
            error_string = getattr(result_msg, "error_string", "")

            if status != GoalStatus.STATUS_SUCCEEDED:
                self._log.error(f"[lift] failed: status={status}, error_string={error_string}")
                return False

            if error_code not in (0, None):
                self._log.error(f"[lift] controller error_code={error_code}, error_string={error_string}")
                return False

            self._log.info(f"[lift] reached {float(position):.3f}")
            return True

        except Exception as exc:
            self._log.error(f"[lift] exception while moving lift: {exc}")
            return False


def robot_state_with_left_seed(
    client: SymmetricDualArmClient,
    left_seed: list[float] | None,
) -> RobotState:
    state = client.current_robot_state()
    if left_seed is None:
        return state

    if len(left_seed) != 7:
        raise ValueError(f"left_seed must have length 7, got {len(left_seed)}")

    names = list(state.joint_state.name)
    positions = list(state.joint_state.position)
    name_to_index = {name: i for i, name in enumerate(names)}

    for joint_name, joint_value in zip(ARM_L_JOINTS, left_seed):
        if joint_name not in name_to_index:
            raise RuntimeError(f"{joint_name} not found in current RobotState")
        positions[name_to_index[joint_name]] = float(joint_value)

    state.joint_state.position = positions
    return state


def compute_left_ik(
    node: Node,
    client: SymmetricDualArmClient,
    ik_client,
    pose: Pose,
    *,
    left_seed: list[float] | None = None,
    timeout_sec: float = 5.0,
) -> list[float]:
    log = node.get_logger()
    if not ik_client.wait_for_service(timeout_sec=timeout_sec):
        raise RuntimeError("Timed out waiting for /compute_ik")

    req = GetPositionIK.Request()
    req.ik_request.group_name = ARM_GROUP[Arm.LEFT]
    req.ik_request.robot_state = robot_state_with_left_seed(client, left_seed)
    req.ik_request.avoid_collisions = True
    req.ik_request.ik_link_name = ARM_EEF[Arm.LEFT]

    stamped = PoseStamped()
    stamped.header.frame_id = BASE_LINK
    stamped.header.stamp = node.get_clock().now().to_msg()
    stamped.pose = pose
    req.ik_request.pose_stamped = stamped
    req.ik_request.timeout = duration_from_seconds(timeout_sec)

    # Some MoveIt versions do not expose this field on PositionIKRequest.
    if hasattr(req.ik_request, "attempts"):
        req.ik_request.attempts = 5

    future = ik_client.call_async(req)
    resp = wait_future(future, timeout_sec + 2.0)

    if resp.error_code.val != MoveItErrorCodes.SUCCESS:
        raise RuntimeError(
            f"LEFT IK failed, error_code={resp.error_code.val}, pose={pose_str(pose)}"
        )

    name_to_pos = dict(zip(resp.solution.joint_state.name, resp.solution.joint_state.position))
    joints = [float(name_to_pos[name]) for name in ARM_L_JOINTS]
    log.info(f"LEFT IK joints: {[round(v, 4) for v in joints]}")
    return joints


def smoothstep(alpha: float) -> float:
    return 3.0 * alpha * alpha - 2.0 * alpha * alpha * alpha


def build_left_waypoint_trajectory(
    start: list[float],
    waypoints: list[list[float]],
    *,
    segment_duration_sec: float,
    points_per_segment: int,
) -> JointTrajectory:
    if len(start) != 7:
        raise ValueError("start must have length 7")
    if not waypoints:
        raise ValueError("at least one waypoint is required")
    if points_per_segment < 2:
        raise ValueError("points_per_segment must be >= 2")
    if segment_duration_sec <= 0.0:
        raise ValueError("segment_duration must be positive")

    traj = JointTrajectory()
    traj.joint_names = list(ARM_L_JOINTS)

    previous = list(start)
    elapsed = 0.0

    for segment_index, target in enumerate(waypoints):
        if len(target) != 7:
            raise ValueError("each waypoint must have length 7")
        for i in range(points_per_segment):
            if segment_index > 0 and i == 0:
                continue
            alpha = i / float(points_per_segment - 1)
            s = smoothstep(alpha)
            point = JointTrajectoryPoint()
            point.positions = [previous[j] + s * (target[j] - previous[j]) for j in range(7)]
            point.time_from_start = duration_from_seconds(elapsed + alpha * segment_duration_sec)
            traj.points.append(point)
        elapsed += segment_duration_sec
        previous = list(target)

    return traj


def print_joint_summary(node: Node, client: SymmetricDualArmClient, title: str) -> None:
    log = node.get_logger()
    log.info(f"==== {title} ====")
    left = client.get_joints(Arm.LEFT)
    right = client.get_joints(Arm.RIGHT)
    if left is None or right is None:
        log.error("joint state unavailable")
        return
    log.info(f"[left]  {dict(zip(ARM_L_JOINTS, [round(v, 4) for v in left]))}")
    log.info(f"[right] {dict(zip(ARM_R_JOINTS, [round(v, 4) for v in right]))}")


def main(args=None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--home-first", action="store_true", help="Override HOME_FIRST=True")
    parser.add_argument("--no-home-first", action="store_true", help="Override HOME_FIRST=False")
    parser.add_argument("--return-home", action="store_true", help="Override RETURN_HOME=True")
    parser.add_argument("--no-return-home", action="store_true", help="Override RETURN_HOME=False")
    parser.add_argument("--plan-only", action="store_true", help="Override PLAN_ONLY=True")
    parser.add_argument("--execute", action="store_true", help="Override PLAN_ONLY=False")
    parser.add_argument("--arrived", action="store_true", help="Override ARRIVED_SIGNAL_RECEIVED=True")
    parser.add_argument("--not-arrived", action="store_true", help="Override ARRIVED_SIGNAL_RECEIVED=False")
    parser.add_argument("--use-lift", action="store_true", help="Override USE_LIFT_ON_ARRIVAL=True")
    parser.add_argument("--no-use-lift", action="store_true", help="Override USE_LIFT_ON_ARRIVAL=False")
    parser.add_argument("--apply-lift-offset", action="store_true", help="Override APPLY_LIFT_OFFSET_TO_PLACE_WAYPOINT=True")
    parser.add_argument("--no-apply-lift-offset", action="store_true", help="Override APPLY_LIFT_OFFSET_TO_PLACE_WAYPOINT=False")
    parser.add_argument("--return-lift-home", action="store_true", help="Override RETURN_LIFT_HOME_AFTER_PLACE=True")
    parser.add_argument("--no-return-lift-home", action="store_true", help="Override RETURN_LIFT_HOME_AFTER_PLACE=False")
    parser.add_argument("--raw-pose-plan", action="store_true", help="Disable task selector policy and plan raw waypoint pose directly")
    parser.add_argument("--prepose-only", action="store_true", help="Plan only task-selector pre-grasp pose, without local target segment")
    parser.add_argument("--include-target", action="store_true", help="Force task-selector local target segment on")
    ns = parser.parse_args(args=args)

    home_first = HOME_FIRST
    if ns.home_first:
        home_first = True
    if ns.no_home_first:
        home_first = False

    return_home = RETURN_HOME
    if ns.return_home:
        return_home = True
    if ns.no_return_home:
        return_home = False

    plan_only = PLAN_ONLY
    if ns.plan_only:
        plan_only = True
    if ns.execute:
        plan_only = False

    arrived_signal_received = ARRIVED_SIGNAL_RECEIVED
    if ns.arrived:
        arrived_signal_received = True
    if ns.not_arrived:
        arrived_signal_received = False

    use_lift_on_arrival = USE_LIFT_ON_ARRIVAL
    if ns.use_lift:
        use_lift_on_arrival = True
    if ns.no_use_lift:
        use_lift_on_arrival = False

    apply_lift_offset_to_place_waypoint = APPLY_LIFT_OFFSET_TO_PLACE_WAYPOINT
    if ns.apply_lift_offset:
        apply_lift_offset_to_place_waypoint = True
    if ns.no_apply_lift_offset:
        apply_lift_offset_to_place_waypoint = False

    return_lift_home_after_place = RETURN_LIFT_HOME_AFTER_PLACE
    if ns.return_lift_home:
        return_lift_home_after_place = True
    if ns.no_return_lift_home:
        return_lift_home_after_place = False

    use_task_selector = USE_TASK_SELECTOR
    if ns.raw_pose_plan:
        use_task_selector = False

    include_task_target = INCLUDE_TASK_TARGET
    if ns.prepose_only:
        include_task_target = False
    if ns.include_target:
        include_task_target = True

    rclpy.init(args=args)
    node = Node("test_dual_place")
    log = node.get_logger()
    client = SymmetricDualArmClient(node, manage_executor=True)

    exit_code = 1
    try:
        log.info("test_dual_place uses an arrived signal, optional lift-down, then previous wp1 place pose")
        client.wait_until_ready(timeout_sec=10.0)
        time.sleep(0.2)
        print_joint_summary(node, client, "Robot state before test_dual_place")

        if home_first:
            log.info("==== home-first requested ====")
            left_home, right_home = client.build_home_trajectories(
                duration_sec=3.0,
                points=max(10, POINTS_PER_SEGMENT),
            )
            home_result = client.execute_both(left_home, right_home, timeout_sec=TIMEOUT_SEC)
            log.info(f"home-first result: {home_result}")
            if not home_result.both_succeeded:
                log.error("home-first failed; stopping")
                sys.exit(1)
            time.sleep(0.5)

        place_name, raw_place_pose = resolve_place_waypoint()
        place_pose = raw_place_pose
        applied_lift_z_offset = 0.0
        if use_lift_on_arrival and apply_lift_offset_to_place_waypoint:
            applied_lift_z_offset = LIFT_PLACE_DOWN
            place_pose = copy_pose_with_z_offset(raw_place_pose, applied_lift_z_offset)

        log.info("==== MODE: test_dual_place ====")
        log.info(f"arrived_signal_received={arrived_signal_received}")
        log.info(f"use_lift_on_arrival={use_lift_on_arrival}")
        log.info(f"apply_lift_offset_to_place_waypoint={apply_lift_offset_to_place_waypoint}")
        log.info(f"return_lift_home_after_place={return_lift_home_after_place}")
        log.info(f"lift target after arrival: {LIFT_PLACE_DOWN:.3f}")
        log.info(f"lift home target after place: {LIFT_HOME:.3f}")
        log.info(f"applied waypoint z offset: {applied_lift_z_offset:.3f}")
        log.info(f"LEFT raw place waypoint {place_name}: {pose_str(raw_place_pose)}")
        log.info(f"LEFT planned place waypoint {place_name}: {pose_str(place_pose)}")

        left_start = client.get_joints(Arm.LEFT)
        right_start = client.get_joints(Arm.RIGHT)
        if left_start is None or right_start is None:
            raise RuntimeError("joint states unavailable")

        if not arrived_signal_received:
            log.info("arrival signal is False; no place motion will be executed")
            exit_code = 0
        else:
            log.info("arrival signal is True; starting place sequence")

            def plan_place_waypoint(name: str, pose: Pose):
                left_traj, right_traj, left_waypoint_joints = client.plan_left_waypoints_then_mirror(
                    [pose],
                    velocity=0.05,
                    acceleration=0.05,
                    segment_duration_sec=SEGMENT_DURATION_SEC,
                    timeout_sec=TIMEOUT_SEC,
                    use_task_selector=use_task_selector,
                    include_task_target=include_task_target,
                    pre_grasp_offset=TASK_PRE_GRASP_OFFSET,
                )

                if not left_waypoint_joints:
                    raise RuntimeError(f"{name}: planner returned no left waypoint joints")

                log.info(f"LEFT {name} final joints: {[round(v, 4) for v in left_waypoint_joints[-1]]}")
                log.info(
                    f"{name}: left trajectory points={len(left_traj.points)}, "
                    f"right trajectory points={len(right_traj.points)}"
                )
                return left_traj, right_traj, left_waypoint_joints[-1]

            if plan_only:
                log.info("plan-only requested; not executing lift or arm controller goals")
                if use_lift_on_arrival:
                    log.info(
                        f"plan-only: would keep current arm posture and move lift to "
                        f"{LIFT_PLACE_DOWN:.3f} over {LIFT_MOVE_DURATION_SEC:.1f}s"
                    )
                else:
                    log.info("plan-only: lift motion disabled by config")
                if use_lift_on_arrival and apply_lift_offset_to_place_waypoint:
                    log.info(
                        f"plan-only: place waypoint z is adjusted by {LIFT_PLACE_DOWN:.3f}; "
                        f"raw={raw_place_pose.position.z:.3f}, planned={place_pose.position.z:.3f}"
                    )
                if use_lift_on_arrival and return_lift_home_after_place:
                    log.info(
                        f"plan-only: after reaching place waypoint, would move lift back to "
                        f"{LIFT_HOME:.3f} over {LIFT_MOVE_DURATION_SEC:.1f}s"
                    )
                plan_place_waypoint(place_name, place_pose)
                exit_code = 0
            else:
                if use_lift_on_arrival:
                    log.info(
                        "==== lift down after arrival: keeping current arm posture, "
                        f"moving lift to {LIFT_PLACE_DOWN:.3f} over {LIFT_MOVE_DURATION_SEC:.1f}s ===="
                    )
                    log.info("No arm trajectory is sent during this lift motion; arms should hold current posture.")
                    lift = LiftTrajectoryClient(node)
                    if not lift.move_to(LIFT_PLACE_DOWN):
                        log.error("lift down failed; stopping before place waypoint")
                        exit_code = 1
                    else:
                        log.info("lift down succeeded; moving arms to place waypoint")
                        left_traj, right_traj, _ = plan_place_waypoint(place_name, place_pose)
                        result = client.execute_both(left_traj, right_traj, timeout_sec=TIMEOUT_SEC)
                        log.info(f"{place_name} result: {result}")
                        log.info(
                            f"Left:  result={result.left.result.value}, "
                            f"status={result.left.status}, message={result.left.message}"
                        )
                        log.info(
                            f"Right: result={result.right.result.value}, "
                            f"status={result.right.status}, message={result.right.message}"
                        )
                        exit_code = 0 if result.both_succeeded else 1

                        if result.both_succeeded and return_lift_home_after_place:
                            log.info(
                                "==== place waypoint reached; returning lift to "
                                f"{LIFT_HOME:.3f} over {LIFT_MOVE_DURATION_SEC:.1f}s ===="
                            )
                            if not lift.move_to(LIFT_HOME):
                                log.error("lift return-home failed after place waypoint")
                                exit_code = 1
                            else:
                                log.info("lift returned to home after place waypoint")
                        elif not result.both_succeeded:
                            log.warn("place waypoint was not reached; skipping lift return-home")
                        elif not return_lift_home_after_place:
                            log.info("lift return-home after place skipped by config")
                else:
                    log.info("==== lift motion skipped by config; moving directly to place waypoint ====")
                    left_traj, right_traj, _ = plan_place_waypoint(place_name, place_pose)
                    result = client.execute_both(left_traj, right_traj, timeout_sec=TIMEOUT_SEC)
                    log.info(f"{place_name} result: {result}")
                    log.info(
                        f"Left:  result={result.left.result.value}, "
                        f"status={result.left.status}, message={result.left.message}"
                    )
                    log.info(
                        f"Right: result={result.right.result.value}, "
                        f"status={result.right.status}, message={result.right.message}"
                    )
                    exit_code = 0 if result.both_succeeded else 1
                    if return_lift_home_after_place:
                        log.info("lift return-home requested, but lift motion was skipped; no lift command sent")

        if return_home:
            log.info("==== return-home requested ====")
            left_home, right_home = client.build_home_trajectories(
                duration_sec=3.0,
                points=max(10, POINTS_PER_SEGMENT),
            )
            result = client.execute_both(left_home, right_home, timeout_sec=TIMEOUT_SEC)
            log.info(f"return-home result: {result}")

        time.sleep(0.5)
        print_joint_summary(node, client, "Robot state after test_dual_place")

    except Exception as exc:
        log.error(f"test_dual_place failed: {exc}")
        log.error(traceback.format_exc())
        exit_code = 1
    finally:
        client.destroy()
        node.destroy_node()
        rclpy.shutdown()

    sys.exit(exit_code)


if __name__ == "__main__":
    main()