green_button_center:
  ros__parameters:
    rgb_topic: /camera_right/camera_right/color/image_rect_raw
    depth_topic: /camera_right/camera_right/depth/image_rect_raw
    rgb_info_topic: /camera_right/camera_right/color/camera_info
    depth_info_topic: /camera_right/camera_right/depth/camera_info
    base_frame: base_link
    rgb_frame: ""
    depth_frame: ""
    camera_name: wrist_right
    min_confidence: 0.3
    bbox_format: xyxy
    select_policy: confidence
    depth_scale: 0.001
    invalid_depth_values: [0, 65535]
    min_depth_m: 0.1
    max_depth_m: 3.0
    pixel_step: 1
    depth_window_px: 5
    use_tf_for_extrinsics: true
    extrinsics_tf_timeout_sec: 0.05
    extrinsics_rotation: [0.9999939203262329, -0.0015899674035608768, -0.003109483979642391, 0.0015913281822577119, 0.9999986290931702, 0.00043518951861187816, 0.003108787816017866, -0.00044013507431373, 0.9999950528144836]
    extrinsics_translation: [-9.677278285380453e-06, 1.0000000656873453e-05, 1.0000000656873453e-05]
    surface_inner_scale: 0.8
    surface_depth_percentile: 50.0
    top_depth_percentile: 35.0
    min_region_valid_points: 10
    endpoint_policy: rightmost
    endpoint_inset_ratio: 0.12
    endpoint_depth_radius_px: 5
    endpoint_depth_percentile: 50.0
    endpoint_output_pixel: endpoint
    endpoint_min_valid_points: 3
    mask_erosion_px: 0
    min_bbox_width_px: 5
    min_bbox_height_px: 5
    max_bbox_width_px: 10000
    max_bbox_height_px: 10000
    intersect_ring_with_mask: false
    ellipse_outer_scale: 1.2
    ellipse_inner_scale: 0.65
    use_detector_center: true
    center_max_offset_ratio: 0.35
    use_plane_fit: true
    plane_fit_min_points: 20
    min_ring_valid_points: 10
    plane_outlier_m: 0.015
    plane_max_mean_residual_m: 0.01
    rim_depth_percentile: 35.0
    hole_center_stabilization_enable: false
    hole_center_smoothing_alpha: 0.30
    hole_center_reset_gate_px: 35.0
    hole_depth_policy: plane
    hole_depth_percentile: 50.0
    hole_depth_smoothing_enable: false
    hole_depth_smoothing_alpha: 0.25
    hole_depth_jump_gate_m: 0.08
    sync_queue_size: 10
    sync_slop: 0.1
    tf_lookup_mode: latest
    tf_timeout_sec: 0.05
    max_future_stamp_sec: 0.03
    allow_latest_tf_fallback: true
    output_stamp_policy: now
    log_targets: true
    publish_debug_image: true
    detections_topic: /detections/wrist/scenario_c/green_button
    out_pose_topic: /perception/wrist/green_button_center
    target_class: green_button
    debug_image_topic: /perception/wrist/debug/green_button_center_image

bolt_top_center:
  ros__parameters:
    rgb_topic: /camera_right/camera_right/color/image_rect_raw
    depth_topic: /camera_right/camera_right/depth/image_rect_raw
    rgb_info_topic: /camera_right/camera_right/color/camera_info
    depth_info_topic: /camera_right/camera_right/depth/camera_info
    base_frame: base_link
    rgb_frame: ""
    depth_frame: ""
    camera_name: wrist_right
    min_confidence: 0.3
    bbox_format: xyxy
    select_policy: confidence
    depth_scale: 0.001
    invalid_depth_values: [0, 65535]
    min_depth_m: 0.1
    max_depth_m: 3.0
    pixel_step: 1
    depth_window_px: 5
    use_tf_for_extrinsics: true
    extrinsics_tf_timeout_sec: 0.05
    extrinsics_rotation: [0.9999939203262329, -0.0015899674035608768, -0.003109483979642391, 0.0015913281822577119, 0.9999986290931702, 0.00043518951861187816, 0.003108787816017866, -0.00044013507431373, 0.9999950528144836]
    extrinsics_translation: [-9.677278285380453e-06, 1.0000000656873453e-05, 1.0000000656873453e-05]
    surface_inner_scale: 0.8
    surface_depth_percentile: 50.0
    top_depth_percentile: 35.0
    min_region_valid_points: 10
    endpoint_policy: rightmost
    endpoint_inset_ratio: 0.12
    endpoint_depth_radius_px: 5
    endpoint_depth_percentile: 50.0
    endpoint_output_pixel: endpoint
    endpoint_min_valid_points: 3
    mask_erosion_px: 0
    min_bbox_width_px: 5
    min_bbox_height_px: 5
    max_bbox_width_px: 10000
    max_bbox_height_px: 10000
    intersect_ring_with_mask: false
    ellipse_outer_scale: 1.2
    ellipse_inner_scale: 0.65
    use_detector_center: true
    center_max_offset_ratio: 0.35
    use_plane_fit: true
    plane_fit_min_points: 20
    min_ring_valid_points: 10
    plane_outlier_m: 0.015
    plane_max_mean_residual_m: 0.01
    rim_depth_percentile: 35.0
    hole_center_stabilization_enable: false
    hole_center_smoothing_alpha: 0.30
    hole_center_reset_gate_px: 35.0
    hole_depth_policy: plane
    hole_depth_percentile: 50.0
    hole_depth_smoothing_enable: false
    hole_depth_smoothing_alpha: 0.25
    hole_depth_jump_gate_m: 0.08
    sync_queue_size: 10
    sync_slop: 0.1
    tf_lookup_mode: latest
    tf_timeout_sec: 0.05
    max_future_stamp_sec: 0.03
    allow_latest_tf_fallback: true
    output_stamp_policy: now
    log_targets: true
    publish_debug_image: true
    detections_topic: /detections/wrist/scenario_d/bolt_top
    out_pose_topic: /perception/wrist/bolt_top_center
    target_class: bolt_top
    debug_image_topic: /perception/wrist/debug/bolt_top_center_image

wheel_hole_center:
  ros__parameters:
    rgb_topic: /camera_right/camera_right/color/image_rect_raw
    depth_topic: /camera_right/camera_right/depth/image_rect_raw
    rgb_info_topic: /camera_right/camera_right/color/camera_info
    depth_info_topic: /camera_right/camera_right/depth/camera_info
    base_frame: base_link
    rgb_frame: ""
    depth_frame: ""
    camera_name: wrist_right
    min_confidence: 0.3
    bbox_format: xyxy
    select_policy: confidence
    depth_scale: 0.001
    invalid_depth_values: [0, 65535]
    min_depth_m: 0.1
    max_depth_m: 3.0
    pixel_step: 1
    depth_window_px: 5
    use_tf_for_extrinsics: true
    extrinsics_tf_timeout_sec: 0.05
    extrinsics_rotation: [0.9999939203262329, -0.0015899674035608768, -0.003109483979642391, 0.0015913281822577119, 0.9999986290931702, 0.00043518951861187816, 0.003108787816017866, -0.00044013507431373, 0.9999950528144836]
    extrinsics_translation: [-9.677278285380453e-06, 1.0000000656873453e-05, 1.0000000656873453e-05]
    surface_inner_scale: 0.8
    surface_depth_percentile: 50.0
    top_depth_percentile: 35.0
    min_region_valid_points: 10
    endpoint_policy: rightmost
    endpoint_inset_ratio: 0.12
    endpoint_depth_radius_px: 5
    endpoint_depth_percentile: 50.0
    endpoint_output_pixel: endpoint
    endpoint_min_valid_points: 3
    mask_erosion_px: 0
    min_bbox_width_px: 5
    min_bbox_height_px: 5
    max_bbox_width_px: 10000
    max_bbox_height_px: 10000
    intersect_ring_with_mask: false
    ellipse_outer_scale: 1.2
    ellipse_inner_scale: 0.65
    use_detector_center: true
    center_max_offset_ratio: 0.35
    use_plane_fit: true
    plane_fit_min_points: 20
    min_ring_valid_points: 10
    plane_outlier_m: 0.015
    plane_max_mean_residual_m: 0.01
    rim_depth_percentile: 35.0
    hole_center_stabilization_enable: true
    hole_center_smoothing_alpha: 0.30
    hole_center_reset_gate_px: 35.0
    hole_depth_policy: median
    hole_depth_percentile: 50.0
    hole_depth_smoothing_enable: true
    hole_depth_smoothing_alpha: 0.25
    hole_depth_jump_gate_m: 0.08
    sync_queue_size: 10
    sync_slop: 0.1
    tf_lookup_mode: latest
    tf_timeout_sec: 0.05
    max_future_stamp_sec: 0.03
    allow_latest_tf_fallback: true
    output_stamp_policy: now
    log_targets: true
    publish_debug_image: true
    detections_topic: /detections/wrist/scenario_d/wheel_hole
    out_pose_topic: /perception/wrist/wheel_hole_center
    target_class: wheel_hole
    debug_image_topic: /perception/wrist/debug/wheel_hole_center_image

bolt_hole_center:
  ros__parameters:
    rgb_topic: /camera_right/camera_right/color/image_rect_raw
    depth_topic: /camera_right/camera_right/depth/image_rect_raw
    rgb_info_topic: /camera_right/camera_right/color/camera_info
    depth_info_topic: /camera_right/camera_right/depth/camera_info
    base_frame: base_link
    rgb_frame: ""
    depth_frame: ""
    camera_name: wrist_right
    min_confidence: 0.3
    bbox_format: xyxy
    select_policy: confidence
    depth_scale: 0.001
    invalid_depth_values: [0, 65535]
    min_depth_m: 0.1
    max_depth_m: 3.0
    pixel_step: 1
    depth_window_px: 5
    use_tf_for_extrinsics: true
    extrinsics_tf_timeout_sec: 0.05
    extrinsics_rotation: [0.9999939203262329, -0.0015899674035608768, -0.003109483979642391, 0.0015913281822577119, 0.9999986290931702, 0.00043518951861187816, 0.003108787816017866, -0.00044013507431373, 0.9999950528144836]
    extrinsics_translation: [-9.677278285380453e-06, 1.0000000656873453e-05, 1.0000000656873453e-05]
    surface_inner_scale: 0.8
    surface_depth_percentile: 50.0
    top_depth_percentile: 35.0
    min_region_valid_points: 10
    endpoint_policy: rightmost
    endpoint_inset_ratio: 0.12
    endpoint_depth_radius_px: 5
    endpoint_depth_percentile: 50.0
    endpoint_output_pixel: endpoint
    endpoint_min_valid_points: 3
    mask_erosion_px: 0
    min_bbox_width_px: 5
    min_bbox_height_px: 5
    max_bbox_width_px: 10000
    max_bbox_height_px: 10000
    intersect_ring_with_mask: false
    ellipse_outer_scale: 1.2
    ellipse_inner_scale: 0.65
    use_detector_center: true
    center_max_offset_ratio: 0.35
    use_plane_fit: true
    plane_fit_min_points: 20
    min_ring_valid_points: 10
    plane_outlier_m: 0.015
    plane_max_mean_residual_m: 0.01
    rim_depth_percentile: 35.0
    hole_center_stabilization_enable: false
    hole_center_smoothing_alpha: 0.30
    hole_center_reset_gate_px: 35.0
    hole_depth_policy: plane
    hole_depth_percentile: 50.0
    hole_depth_smoothing_enable: false
    hole_depth_smoothing_alpha: 0.25
    hole_depth_jump_gate_m: 0.08
    sync_queue_size: 10
    sync_slop: 0.1
    tf_lookup_mode: latest
    tf_timeout_sec: 0.05
    max_future_stamp_sec: 0.03
    allow_latest_tf_fallback: true
    output_stamp_policy: now
    log_targets: true
    publish_debug_image: true
    detections_topic: /detections/wrist/scenario_d/bolt_hole
    out_pose_topic: /perception/wrist/bolt_hole_center
    target_class: bolt_hole
    debug_image_topic: /perception/wrist/debug/bolt_hole_center_image

drill_endpoint:
  ros__parameters:
    rgb_topic: /camera_right/camera_right/color/image_rect_raw
    depth_topic: /camera_right/camera_right/depth/image_rect_raw
    rgb_info_topic: /camera_right/camera_right/color/camera_info
    depth_info_topic: /camera_right/camera_right/depth/camera_info
    base_frame: base_link
    rgb_frame: ""
    depth_frame: ""
    camera_name: wrist_right
    min_confidence: 0.3
    bbox_format: xyxy
    select_policy: confidence
    depth_scale: 0.001
    invalid_depth_values: [0, 65535]
    min_depth_m: 0.1
    max_depth_m: 3.0
    pixel_step: 1
    depth_window_px: 5
    use_tf_for_extrinsics: true
    extrinsics_tf_timeout_sec: 0.05
    extrinsics_rotation: [0.9999939203262329, -0.0015899674035608768, -0.003109483979642391, 0.0015913281822577119, 0.9999986290931702, 0.00043518951861187816, 0.003108787816017866, -0.00044013507431373, 0.9999950528144836]
    extrinsics_translation: [-9.677278285380453e-06, 1.0000000656873453e-05, 1.0000000656873453e-05]
    surface_inner_scale: 0.8
    surface_depth_percentile: 50.0
    top_depth_percentile: 35.0
    min_region_valid_points: 10
    endpoint_policy: rightmost
    endpoint_inset_ratio: 0.12
    endpoint_depth_radius_px: 5
    endpoint_depth_percentile: 50.0
    endpoint_output_pixel: endpoint
    endpoint_min_valid_points: 3
    mask_erosion_px: 0
    min_bbox_width_px: 5
    min_bbox_height_px: 5
    max_bbox_width_px: 10000
    max_bbox_height_px: 10000
    intersect_ring_with_mask: false
    ellipse_outer_scale: 1.2
    ellipse_inner_scale: 0.65
    use_detector_center: true
    center_max_offset_ratio: 0.35
    use_plane_fit: true
    plane_fit_min_points: 20
    min_ring_valid_points: 10
    plane_outlier_m: 0.015
    plane_max_mean_residual_m: 0.01
    rim_depth_percentile: 35.0
    hole_center_stabilization_enable: false
    hole_center_smoothing_alpha: 0.30
    hole_center_reset_gate_px: 35.0
    hole_depth_policy: plane
    hole_depth_percentile: 50.0
    hole_depth_smoothing_enable: false
    hole_depth_smoothing_alpha: 0.25
    hole_depth_jump_gate_m: 0.08
    sync_queue_size: 10
    sync_slop: 0.1
    tf_lookup_mode: latest
    tf_timeout_sec: 0.05
    max_future_stamp_sec: 0.03
    allow_latest_tf_fallback: true
    output_stamp_policy: now
    log_targets: true
    publish_debug_image: true
    detections_topic: /detections/wrist/scenario_d/drill
    out_pose_topic: /perception/wrist/drill_endpoint
    target_class: drill
    debug_image_topic: /perception/wrist/debug/drill_endpoint_image
