bolt_top_detector:
  ros__parameters:
    part_name: bolt_top
    head_topic: /zed/zed_node/rgb/image_rect_color
    wrist_left_topic: /camera_left/camera_left/color/image_rect_raw
    wrist_right_topic: /camera_right/camera_right/color/image_rect_raw
    camera_name: zed
    image_topic: /zed/zed_node/rgb/image_rect_color
    detections_topic: /detections/scenario_d/bolt_top
    detections_msg_type: single
    mode: match
    parent_class: bolt
    child_class: bolt_top
    index_by_x: false
    fit_ellipse: true
    conf_threshold: 0.3
    iou_threshold: 0.35
    imgsz: 640
