pipe_detector:
  ros__parameters:
    part_name: pipe
    head_topic: /zed/zed_node/rgb/image_rect_color
    wrist_left_topic: /camera_left/camera_left/color/image_rect_raw
    wrist_right_topic: /camera_right/camera_right/color/image_rect_raw
    detections_topic: /detections/scenario_c/pipe
    mode: match
    parent_class: pipe
    child_class: pipe_opening
    index_by_x: true
    fit_ellipse: true
    conf_threshold: 0.1
    iou_threshold: 0.35
    imgsz: 640
